# Generated by Django 5.0.6 on 2024-11-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiraPlusSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id_residente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='pago',
            name='num_departamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MiraPlusSite.departamento'),
        ),
        migrations.AddField(
            model_name='pago',
            name='periodo_pago',
            field=models.DateField(default=None),
        ),
    ]
