# Generated by Django 5.0.6 on 2024-11-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiraPlusSite', '0003_alter_departamento_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Disponible', 'Disponible'), ('En Mantencion', 'En Mantencion')], max_length=80),
        ),
    ]
