# Generated by Django 5.0.6 on 2024-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiraPlusSite', '0004_alter_departamento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('En Mantencion', 'En Mantencion')], max_length=80),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pago duplicado', 'Pago duplicado'), ('Pago exitoso dentro del plazo', 'Pago exitoso dentro del plazo'), ('Pago exitoso fuera del plazo', 'Pago exitoso fuera del plazo')], max_length=80),
        ),
    ]
