# Generated by Django 5.0.6 on 2024-11-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiraPlusSite', '0005_alter_departamento_estado_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado',
            field=models.CharField(choices=[('En Mantencion', 'En Mantencion'), ('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], max_length=80),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pago exitoso fuera del plazo', 'Pago exitoso fuera del plazo'), ('Pago duplicado', 'Pago duplicado'), ('Pago exitoso dentro del plazo', 'Pago exitoso dentro del plazo')], max_length=80),
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('estado', models.CharField(choices=[('Deuda pendiente', 'Deuda pendiente'), ('Deuda pagada', 'Deuda pagada')], max_length=80)),
                ('fecha_deuda', models.DateField()),
                ('periodo_deuda', models.DateField(default=None)),
                ('num_departamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MiraPlusSite.departamento')),
            ],
        ),
    ]
