# Generated by Django 5.1.3 on 2024-11-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiraPlusSite', '0007_alter_departamento_estado_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('En Mantencion', 'En Mantencion'), ('Disponible', 'Disponible')], max_length=80),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='estado',
            field=models.CharField(choices=[('Deuda pagada', 'Deuda pagada'), ('Deuda pendiente', 'Deuda pendiente')], max_length=80),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pago duplicado', 'Pago duplicado'), ('Pago exitoso fuera del plazo', 'Pago exitoso fuera del plazo'), ('Pago exitoso dentro del plazo', 'Pago exitoso dentro del plazo')], max_length=80),
        ),
    ]
